save arena contract
ImpulseDAO/AArena pull request #14
Opened 2023-07-20 16:29 UTC by cute0laf

2023-07-20 21:31 UTC, tmcgroul requested changes

2023-07-20 21:31 UTC, tmcgroul commented on contracts/mint/src/lib.rs
> +    let arean_contract: ActorId = msg::load().expect("Can't load id of arena contract");
arena contract requires address of mint contract. it makes impossible to instantiate mint contract before arena...
my suggestion is to make `arena_contract` field optional and assign arena address via additional action - smth like `MintAction::SetArena`

2023-07-20 21:31 UTC, tmcgroul commented on contracts/mint/src/lib.rs
> +    let arean_contract: ActorId = msg::load().expect("Can't load id of arena contract");
we also should check that the assignment is done by the owner of mint contract

2023-07-22 08:47 UTC, oe2fast4u approved these changes

2023-07-22 08:47 UTC, merged